server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: spring-boot-kubernetes-mysql
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/app_db
#    username: db_user
#    password: db_user_pass
#    driver-class-name: com.mysql.cj.jdbc.Driver