---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-boot-kubernetes-mysql
        version: 6.2.0
      name: spring-boot-kubernetes-mysql
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
          nodePort: 31371
      type: NodePort
      selector:
        app: spring-boot-kubernetes-mysql
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: spring-boot-kubernetes-mysql
      labels:
        account: spring-boot-kubernetes-mysql
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: spring-boot-kubernetes-mysql
        version: 6.2.0
      name: spring-boot-kubernetes-mysql
    spec:
      selector:
        matchLabels:
          app: spring-boot-kubernetes-mysql
      template:
        metadata:
          labels:
            app: spring-boot-kubernetes-mysql
            version: 6.2.0
        spec:
          serviceAccountName: spring-boot-kubernetes-mysql
          containers:
            - name: spring-boot-kubernetes-mysql
              image: ashutoshsahoo/spring-boot-kubernetes-mysql:6.2.0
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "1"
                requests:
                  memory: "100Mi"
                  cpu: "100m"
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: k8s
                - name: SPRING_DATASOURCE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: mysql-config
                      key: MYSQL_DATABASE_URL
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_USER
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_PASSWORD
              securityContext:
                # runAsUser: 1000
                # readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
              readinessProbe:
                httpGet:
                  path:  /api/v1/actuator/health/readiness
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 2
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path:  /api/v1/actuator/health/liveness
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 15
                timeoutSeconds: 2
                failureThreshold: 5
