pipeline {
    agent any
    tools {
        maven 'Maven 3.5.2'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build Application') {
            steps {
                sh 'mvn clean install'
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
		
		stage ('Build Docker Image') {
            steps {
                sh 'mvn k8s:build k8s:resource'
            }
        }
		
		stage ('Kubernetes Deploy') {
            steps {
                sh 'mvn k8s:deploy'
            }
        }
    }
}
